language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_install:
  - touch database/database.sqlite
  - cp .env.travis .env
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --dev --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate:fresh --seed

script:
  #- vendor/bin/phpunit --verbose
  - vendor/bin/grumphp run
